spring:
  data:
    mongodb:
      database: ${MONGODB_DB}
      uri: ${MONGODB_URI}
  servlet:
    multipart:
      location: uploads/
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 50MB

ewardrobe:
  app:
    SecretKey: ${SECRET_KEY}

cloudinary:
  cloud-name: ${CLOUD_NAME}
  api-key: ${API_KEY}
  api-secret: ${API_SECRET}

